# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT0iMnjOhlNRO5VA7PoS3E6etH8dJsib
"""

import sys
import cv2
import numpy as np


SEG_ORDER = "abcdefg"

SYMBOL_TO_SEG = {
    "0": "abcdef",
    "1": "bc",
    "2": "abdeg",
    "3": "abcdg",
    "4": "bcfg",
    "5": "acdfg",
    "6": "acdefg",
    "7": "abc",
    "8": "abcdefg",
    "9": "abcdfg",
    "A": "abcefg",
    "b": "cdefg",
    "C": "adef",
    "d": "bcdeg",
    "E": "adefg",
    "F": "aefg",
    "PLUS_LEFT": "bcg",
    "MINUS": "g",
    "MUL": "a",
    "EQ": "dg",
}

SEG_TO_SYMBOL = {"".join(sorted(v)): k for k, v in SYMBOL_TO_SEG.items()}


def hex_value(ch):
    if ch in "0123456789":
        return int(ch)
    return {"A": 10, "b": 11, "C": 12, "d": 13, "E": 14, "F": 15}.get(ch)


def parse_number(tokens):
    if not tokens:
        return None
    val = 0
    for t in tokens:
        d = hex_value(t)
        if d is None:
            return None
        val = val * 16 + d
    return val


def convert_symbols(raw):
    out = []
    i = 0
    while i < len(raw):
        if raw[i] == "PLUS_LEFT":
            if i + 1 < len(raw) and raw[i + 1] == "MINUS":
                out.append("+")
                i += 2
            else:
                return None
        elif raw[i] == "MINUS":
            out.append("-")
            i += 1
        elif raw[i] == "MUL":
            out.append("*")
            i += 1
        elif raw[i] == "EQ":
            out.append("=")
            i += 1
        else:
            out.append(raw[i])
            i += 1
    return out


def evaluate(tokens):
    if tokens is None or "=" not in tokens:
        return False

    p = tokens.index("=")
    left = tokens[:p]
    right = tokens[p + 1:]

    rhs = parse_number(right)
    if rhs is None:
        return False

    nums = []
    ops = []
    cur = []

    for t in left:
        if t in "+-*":
            num = parse_number(cur)
            if num is None:
                return False
            nums.append(num)
            ops.append(t)
            cur = []
        else:
            cur.append(t)

    num = parse_number(cur)
    if num is None:
        return False
    nums.append(num)

    i = 0
    while i < len(ops):
        if ops[i] == "*":
            nums[i] *= nums[i + 1]
            del nums[i + 1]
            del ops[i]
        else:
            i += 1

    res = nums[0]
    for op, val in zip(ops, nums[1:]):
        if op == "+":
            res += val
        elif op == "-":
            res -= val

    return res == rhs


def mask_lights(img):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    b, g, r = cv2.split(img)

    mx = np.maximum(np.maximum(r, g), b)
    mn = np.minimum(np.minimum(r, g), b)

    h, s, v = cv2.split(hsv)

    mask = ((s > 45) & (v > 60) & ((mx - mn) > 25)).astype(np.uint8) * 255

    k = np.ones((5, 5), np.uint8)
    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, k)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, k)

    n, labels, stats, _ = cv2.connectedComponentsWithStats(mask, 8)
    clean = np.zeros_like(mask)

    areas = [stats[i, cv2.CC_STAT_AREA] for i in range(1, n)]
    if not areas:
        return clean

    med = np.median(areas)
    min_area = max(25, med * 0.08)

    for i in range(1, n):
        if stats[i, cv2.CC_STAT_AREA] >= min_area:
            clean[labels == i] = 255

    return clean


def get_points(mask):
    y, x = np.where(mask > 0)
    return np.column_stack([x, y]).astype(np.float32)


def pca_axes(points):
    c = points.mean(axis=0)
    q = points - c
    cov = np.cov(q.T)
    vals, vecs = np.linalg.eigh(cov)
    x_axis = vecs[:, np.argmax(vals)]
    x_axis = x_axis / np.linalg.norm(x_axis)
    y_axis = np.array([-x_axis[1], x_axis[0]], dtype=np.float32)
    return c, x_axis.astype(np.float32), y_axis.astype(np.float32)


def project(points, center, x_axis, y_axis):
    q = points - center
    x = q @ x_axis
    y = q @ y_axis
    return x, y


def split_by_x(xvals, close_size):
    xmin = int(np.floor(xvals.min()))
    xmax = int(np.ceil(xvals.max()))
    w = xmax - xmin + 1
    if w <= 0:
        return []

    hist = np.zeros(w, dtype=np.uint8)
    xs = np.clip((xvals - xmin).astype(np.int32), 0, w - 1)
    hist[xs] = 255

    kernel = np.ones((1, close_size), np.uint8)
    h2 = cv2.morphologyEx(hist.reshape(1, -1), cv2.MORPH_CLOSE, kernel).ravel()

    intervals = []
    in_run = False
    start = 0

    for i, v in enumerate(h2):
        if v and not in_run:
            start = i
            in_run = True
        elif not v and in_run:
            if i - start > 5:
                intervals.append((start + xmin, i + xmin))
            in_run = False

    if in_run:
        intervals.append((start + xmin, w + xmin))

    return intervals


def classify_display(px, py):
    if len(px) < 10:
        return ""

    xmin, xmax = px.min(), px.max()
    ymin, ymax = py.min(), py.max()

    W = max(xmax - xmin, 1e-6)
    H = max(ymax - ymin, 1e-6)

    nx = (px - xmin) / W
    ny = (py - ymin) / H

    regions = {
        "a": (0.20, 0.80, 0.00, 0.24),
        "b": (0.58, 1.00, 0.08, 0.54),
        "c": (0.58, 1.00, 0.46, 0.92),
        "d": (0.20, 0.80, 0.76, 1.00),
        "e": (0.00, 0.42, 0.46, 0.92),
        "f": (0.00, 0.42, 0.08, 0.54),
        "g": (0.20, 0.80, 0.36, 0.64),
    }

    active = []

    for seg, (x1, x2, y1, y2) in regions.items():
        inside = (nx >= x1) & (nx <= x2) & (ny >= y1) & (ny <= y2)
        ratio = inside.sum() / len(nx)
        if ratio > 0.035:
            active.append(seg)

    return "".join(active)


def detect_segments(points, center, x_axis, y_axis, close_size):
    x, y = project(points, center, x_axis, y_axis)
    intervals = split_by_x(x, close_size)

    result = []

    for a, b in intervals:
        idx = (x >= a) & (x <= b)
        if idx.sum() < 20:
            continue

        segs = classify_display(x[idx], y[idx])
        if segs:
            result.append((a, "".join(sorted(segs))))

    result.sort(key=lambda z: z[0])
    return [r[1] for r in result]


def find_broken(observed):
    for i in range(len(observed)):
        original = set(observed[i])

        for seg in SEG_ORDER:
            fixed = set(original)

            if seg in fixed:
                fixed.remove(seg)
            else:
                fixed.add(seg)

            candidate = observed[:]
            candidate[i] = "".join(sorted(fixed))

            raw = []
            ok = True

            for s in candidate:
                key = "".join(sorted(s))
                if key not in SEG_TO_SYMBOL:
                    ok = False
                    break
                raw.append(SEG_TO_SYMBOL[key])

            if not ok:
                continue

            tokens = convert_symbols(raw)

            if evaluate(tokens):
                return i + 1, seg, True

    return 1, "a", False


def score_candidate(observed):
    known = 0
    for s in observed:
        if "".join(sorted(s)) in SEG_TO_SYMBOL:
            known += 1

    _, _, valid = find_broken(observed)
    return (1 if valid else 0, known, len(observed))


def solve(path):
    img = cv2.imread(path)
    if img is None:
        print(0)
        print()
        print("1 a")
        return

    mask = mask_lights(img)
    points = get_points(mask)

    if len(points) == 0:
        print(0)
        print()
        print("1 a")
        return

    center, x_axis, y_axis = pca_axes(points)

    candidates = []

    for sx in [1, -1]:
        for sy in [1, -1]:
            xa = x_axis * sx
            ya = y_axis * sy

            for close_size in [8, 12, 16, 24, 32, 48, 64, 80]:
                obs = detect_segments(points, center, xa, ya, close_size)

                if 1 <= len(obs) <= 16:
                    candidates.append((score_candidate(obs), obs))

    if not candidates:
        print(0)
        print()
        print("1 a")
        return

    candidates.sort(key=lambda z: z[0], reverse=True)
    observed = candidates[0][1]

    broken_display, broken_segment, _ = find_broken(observed)

    print(len(observed))
    print(" ".join(observed))
    print(broken_display, broken_segment)


def main():
    path = sys.stdin.readline().strip()
    solve(path)


if __name__ == "__main__":
    main()