# -*- coding: utf-8 -*-
"""Untitled62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WT0iMnjOhlNRO5VA7PoS3E6etH8dJsib
"""

import sys
import cv2
import numpy as np


SEG_ORDER = "abcdefg"

SYMBOL_TO_SEG = {
    "0": "abcdef",
    "1": "bc",
    "2": "abdeg",
    "3": "abcdg",
    "4": "bcfg",
    "5": "acdfg",
    "6": "acdefg",
    "7": "abc",
    "8": "abcdefg",
    "9": "abcdfg",
    "A": "abcefg",
    "b": "cdefg",
    "C": "adef",
    "d": "bcdeg",
    "E": "adefg",
    "F": "aefg",
    "PLUS_L": "bcg",
    "MINUS": "g",
    "MUL": "a",
    "EQ": "dg",
}

SEG_TO_SYMBOL = {"".join(sorted(v)): k for k, v in SYMBOL_TO_SEG.items()}


def hex_value(ch):
    if ch in "0123456789":
        return int(ch)
    return {"A": 10, "b": 11, "C": 12, "d": 13, "E": 14, "F": 15}.get(ch)


def parse_number(tokens):
    if not tokens:
        return None
    value = 0
    for t in tokens:
        d = hex_value(t)
        if d is None:
            return None
        value = value * 16 + d
    return value


def convert_symbols(raw):
    tokens = []
    i = 0
    while i < len(raw):
        if raw[i] == "PLUS_L":
            if i + 1 < len(raw) and raw[i + 1] == "MINUS":
                tokens.append("+")
                i += 2
            else:
                return None
        elif raw[i] == "MINUS":
            tokens.append("-")
            i += 1
        elif raw[i] == "MUL":
            tokens.append("*")
            i += 1
        elif raw[i] == "EQ":
            tokens.append("=")
            i += 1
        else:
            tokens.append(raw[i])
            i += 1
    return tokens


def evaluate(tokens):
    if tokens is None or "=" not in tokens:
        return False

    eq = tokens.index("=")
    left = tokens[:eq]
    right = tokens[eq + 1:]

    rhs = parse_number(right)
    if rhs is None:
        return False

    nums = []
    ops = []
    cur = []

    for t in left:
        if t in "+-*":
            n = parse_number(cur)
            if n is None:
                return False
            nums.append(n)
            ops.append(t)
            cur = []
        else:
            cur.append(t)

    n = parse_number(cur)
    if n is None:
        return False
    nums.append(n)

    i = 0
    while i < len(ops):
        if ops[i] == "*":
            nums[i] *= nums[i + 1]
            del nums[i + 1]
            del ops[i]
        else:
            i += 1

    res = nums[0]
    for op, val in zip(ops, nums[1:]):
        if op == "+":
            res += val
        elif op == "-":
            res -= val

    return res == rhs


def make_mask(img):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    b, g, r = cv2.split(img)
    mx = np.maximum(np.maximum(r, g), b)
    mn = np.minimum(np.minimum(r, g), b)

    mask1 = (s > 35) & (v > 45) & ((mx - mn) > 20)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    mask2 = gray > 245

    mask = (mask1 | mask2).astype(np.uint8) * 255

    k3 = np.ones((3, 3), np.uint8)
    k5 = np.ones((5, 5), np.uint8)

    mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, k3)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, k5)

    n, labels, stats, _ = cv2.connectedComponentsWithStats(mask, 8)
    clean = np.zeros_like(mask)

    areas = []
    for i in range(1, n):
        area = stats[i, cv2.CC_STAT_AREA]
        if area >= 10:
            areas.append(area)

    if not areas:
        return clean

    med = np.median(areas)
    min_area = max(12, med * 0.04)

    for i in range(1, n):
        if stats[i, cv2.CC_STAT_AREA] >= min_area:
            clean[labels == i] = 255

    return clean


def get_points(mask):
    y, x = np.where(mask > 0)
    return np.column_stack([x, y]).astype(np.float32)


def pca_axes(points):
    c = points.mean(axis=0)
    q = points - c
    cov = np.cov(q.T)
    vals, vecs = np.linalg.eigh(cov)
    x_axis = vecs[:, np.argmax(vals)]
    x_axis = x_axis / np.linalg.norm(x_axis)
    y_axis = np.array([-x_axis[1], x_axis[0]], dtype=np.float32)
    return c.astype(np.float32), x_axis.astype(np.float32), y_axis.astype(np.float32)


def project(points, center, x_axis, y_axis):
    q = points - center
    return q @ x_axis, q @ y_axis


def split_intervals(xvals, close_size):
    xmin = int(np.floor(xvals.min()))
    xmax = int(np.ceil(xvals.max()))
    w = xmax - xmin + 1
    if w <= 0:
        return []

    hist = np.zeros(w, dtype=np.uint8)
    xs = np.clip((xvals - xmin).astype(np.int32), 0, w - 1)
    hist[xs] = 255

    kernel = np.ones((1, close_size), np.uint8)
    closed = cv2.morphologyEx(hist.reshape(1, -1), cv2.MORPH_CLOSE, kernel).ravel()

    intervals = []
    inside = False
    start = 0

    for i, val in enumerate(closed):
        if val and not inside:
            start = i
            inside = True
        elif not val and inside:
            if i - start > 4:
                intervals.append((start + xmin, i + xmin))
            inside = False

    if inside:
        intervals.append((start + xmin, w + xmin))

    return intervals


def classify(px, py, interval, global_ymin, global_ymax, mode):
    if len(px) < 8:
        return ""

    x1, x2 = interval
    W = max(x2 - x1, 1e-6)

    if mode == "global":
        ymin, ymax = global_ymin, global_ymax
    else:
        ymin, ymax = py.min(), py.max()

    H = max(ymax - ymin, 1e-6)

    nx = (px - x1) / W
    ny = (py - ymin) / H

    regions = {
        "a": (0.18, 0.82, 0.00, 0.23),
        "b": (0.57, 1.00, 0.07, 0.53),
        "c": (0.57, 1.00, 0.47, 0.93),
        "d": (0.18, 0.82, 0.77, 1.00),
        "e": (0.00, 0.43, 0.47, 0.93),
        "f": (0.00, 0.43, 0.07, 0.53),
        "g": (0.18, 0.82, 0.36, 0.64),
    }

    active = []

    for seg, (xa, xb, ya, yb) in regions.items():
        inside = (nx >= xa) & (nx <= xb) & (ny >= ya) & (ny <= yb)
        ratio = inside.sum() / len(nx)

        if mode == "global":
            threshold = 0.025
        else:
            threshold = 0.040

        if ratio > threshold:
            active.append(seg)

    return "".join(sorted(active))


def detect(points, center, x_axis, y_axis, close_size, mode):
    x, y = project(points, center, x_axis, y_axis)

    gymin, gymax = np.percentile(y, [1, 99])
    intervals = split_intervals(x, close_size)

    result = []

    for a, b in intervals:
        idx = (x >= a) & (x <= b)
        if idx.sum() < 8:
            continue

        segs = classify(x[idx], y[idx], (a, b), gymin, gymax, mode)
        if segs:
            result.append((a, segs))

    result.sort(key=lambda z: z[0])
    return [r[1] for r in result]


def raw_symbols(observed):
    raw = []
    for s in observed:
        key = "".join(sorted(s))
        if key not in SEG_TO_SYMBOL:
            return None
        raw.append(SEG_TO_SYMBOL[key])
    return raw


def find_broken(observed):
    for i in range(len(observed)):
        original = set(observed[i])

        for seg in SEG_ORDER:
            fixed = set(original)

            if seg in fixed:
                fixed.remove(seg)
            else:
                fixed.add(seg)

            candidate = observed[:]
            candidate[i] = "".join(sorted(fixed))

            raw = raw_symbols(candidate)
            if raw is None:
                continue

            tokens = convert_symbols(raw)
            if evaluate(tokens):
                return i + 1, seg, True

    return 1, "a", False


def candidate_score(observed):
    if not (1 <= len(observed) <= 16):
        return (-10, -10, -10)

    known = 0
    for s in observed:
        if "".join(sorted(s)) in SEG_TO_SYMBOL:
            known += 1

    bd, bs, valid = find_broken(observed)

    raw = raw_symbols(observed)
    plus_bonus = 0
    eq_bonus = 0

    if raw is not None:
        if "EQ" in raw:
            eq_bonus = 1
        for i in range(len(raw) - 1):
            if raw[i] == "PLUS_L" and raw[i + 1] == "MINUS":
                plus_bonus += 1

    return (
        100 if valid else 0,
        known,
        eq_bonus,
        plus_bonus,
        len(observed),
    )


def solve(path):
    img = cv2.imread(path, cv2.IMREAD_COLOR)

    if img is None:
        print(0)
        print()
        print("1 a")
        return

    mask = make_mask(img)
    points = get_points(mask)

    if len(points) == 0:
        print(0)
        print()
        print("1 a")
        return

    center, x_axis, y_axis = pca_axes(points)

    candidates = []

    for sx in [1, -1]:
        for sy in [1, -1]:
            xa = x_axis * sx
            ya = y_axis * sy

            for close_size in [5, 8, 10, 12, 16, 20, 24, 32, 40, 48, 64, 80, 100]:
                for mode in ["global", "local"]:
                    obs = detect(points, center, xa, ya, close_size, mode)
                    if 1 <= len(obs) <= 16:
                        candidates.append((candidate_score(obs), obs))

    if not candidates:
        print(0)
        print()
        print("1 a")
        return

    candidates.sort(key=lambda x: x[0], reverse=True)
    observed = candidates[0][1]

    broken_display, broken_segment, _ = find_broken(observed)

    print(len(observed))
    print(" ".join(observed))
    print(broken_display, broken_segment)


def main():
    path = sys.stdin.readline().strip()
    solve(path)


if __name__ == "__main__":
    main()